version: 2.1

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-ssl:release
    steps:
      - checkout
      - run:
          make config=debug ssl=0.9.0 test examples && make config=release ssl=0.9.0 test examples

  vs-ponyc-master:
    docker:
      - image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-ssl:latest
    steps:
      - checkout
      - run:
          make config=debug ssl=0.9.0 test examples && make config=release ssl=0.9.0 test examples

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master
