version: 2.1

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - run: apt update
      - run: apt install -y libpcre2-dev libssl-dev make git
      - checkout
      - run: 
          make config=debug clean test examples && make config=release clean test examples

  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt update
      - run: apt install -y libpcre2-dev libssl-dev make git
      - checkout
      - run:
          make config=debug clean test examples && make config=release clean test examples

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master
